### ISSUE TITLE
Make the muscle loading screen more obvious

### ISSUE THREAD

**Issue by Vincenius** [Vincenius/workout-lol#13]
when opening the muscles screen for the first time, it's fetching the amount of exercises per muscle to disable muscles without exercises. It has kind of a subtle css animation as a loading indicator.

I think it might not be obvious to everyone that it's loading and people might think it's not working, bc it's not reacting. Maybe there is a better way to display that it's loading

**Comment by Snouzy** [comment]
Maybe we should not display the svg and: 
1) some random motivation text hard coded
2) some motivation text based on the equipment selected, or not (via chatgpt)

Let the svg here and : 
3) Animate / flash more and add a text above

I'll go for the 1, we could generate 100 / 200 citations and import it in the project. 
The 2) will be another loader to get the citation though chatGPT

**Comment by Vincenius** [comment]
Looks good - let's do it like this 👍

**Comment by Snouzy** [comment]
Super. Assign it to me i'll do it 💪

**Comment by Snouzy** [comment]
This feature is in proposal mode in #16

**Comment by Vincenius** [comment]
Looks awesome! Thanks!
