### ISSUE TITLE
[Bug] Lately the workout is not marked as complete for me

### ISSUE THREAD

**Issue by Vincenius** [Vincenius/workout-lol#14]
on firefox - maybe it's related to multiple workouts (with the same exercises)

**Comment by Snouzy** [comment]
mh seems to be working on my side : 
![screenshot-2023-06-16_13h49m10s](https://github.com/Vincenius/workout-lol/assets/32961176/5fe38c38-0872-4252-be31-198dbb15beba)

Firefox 114.0.1

**Comment by Vincenius** [comment]
idk sometimes it worked and sometimes not - let's see if this is fixed for me with the new update of accounts

**Comment by Vincenius** [comment]
I could actually reproduce while working on the last issue. It was a problem with the sorting of user workouts, which caused the wrong one to be set to complete. Should be fixed now :)
