### ISSUE TITLE
Add more social logins

### ISSUE THREAD

**Issue by Vincenius** [Vincenius/workout-lol#18]
Add google social login

should I add another?

**Comment by Snouzy** [comment]
do you got some traction from twitter ?

**Comment by Vincenius** [comment]
Yeah twitter would make sense 🤔 I know that they charge for their API now but I'll investigate if the social login would be still for free

**Comment by Vincenius** [comment]
almost done with the google login - I should get it done tomorrow :) The other social logins should be easy afterward

ps. we already have 12 users signed-up

**Comment by Snouzy** [comment]
GJ men. that should encourage the laziest of us ahah 💪

**Comment by Vincenius** [comment]
Google login is done! I'll keep this open to add more

**Comment by Vincenius** [comment]
Twitter is also added now :)
I also checked Facebook but they want a verified business profile and you need to submit the app for review and stuff - too much effort in my opinion
