### ISSUE TITLE
Public profiles

### ISSUE THREAD

**Issue by Vincenius** [Vincenius/workout-lol#22]
How about allowing users to add an (optional?) username to create public profile pages "workout.lol/u/your_username".
This would allow people to share their profile and progress and workouts they created.

We could also think of a way to make them more beautiful :)

**Comment by Snouzy** [comment]
That's a good idea. So hype about this feature. 
We could use the [Dynamic OG of nextJS 13 ](https://nextjs.org/blog/next-13-3#dynamic-open-graph-image-generation), with his username, and something pretty, so the shared link will be beautiful !! 🤯

**Comment by Snouzy** [comment]
So what should we integrate in the shared link ? 
- username 
- Workouts completed 
- We could compute the X days in a row ? => That could be a feature in his own, like Kindle which reminds you to go to the app so you don't break your set. Example: You've been reading for 5 days, don't break the series! 
- Most prefered day to workout ?

**Comment by Vincenius** [comment]
Those are great ideas! I would display the page the user also sees on /profile.
For the streak, we could also allow the user to set an amount of workout per week / how many pause days.
We could also add a leaderboard to compare with other people for different timeframes.

Another idea for the future is to add badges/achievements/trophies for more gamification 😄 like
"Do three workouts"
"Never skip leg day" (doing like 10 leg exercises)
etc.

Let's create new issues for those additional ideas once the public profile is done :)

**Comment by Snouzy** [comment]
Yeah.
So first just to be able to share his profile to `workout.lol/u/your_username`.

What about generating a random username at each register and allow user to change it via the /profile page ?

**Comment by Vincenius** [comment]
Yeah good idea - we could use something like [random-word-slugs](https://www.npmjs.com/package/random-word-slugs) for that :)

**Comment by Snouzy** [comment]
I'll do it today

**Comment by Vincenius** [comment]
Feel free to create more issues for the additional profile things we talked about :)
