### ISSUE TITLE
Motivate people to donate by displaying them

### ISSUE THREAD

**Issue by Vincenius** [Vincenius/workout-lol#26]
I created a Ko-Fi page for workout.lol : [https://ko-fi.com/workout_lol](https://ko-fi.com/workout_lol)
First, we could improve how we display the link in the footer - we could add the official kofi button.

We could also offer a special symbol on their profile for people that donate, like lichess does:
<img width="295" alt="Screenshot 2023-06-23 at 08 36 15" src="https://github.com/Vincenius/workout-lol/assets/43953403/96a43087-8374-4b2d-9ace-fca0715e9587">

Additionally, we could show them in the footer with a link or on an extra "sponsors" page

**Comment by Snouzy** [comment]
That's nice. 
Idea : 
< 5$ => one dumbell 
5 < $ < 10 => 2 crossed dumbbells
10 < $ < 20 => 1 barbell
> 20$ => 2 crossed barbells

**Comment by Vincenius** [comment]
I think it would be easiest to do it manually first :)
