### ISSUE TITLE
Improve video size on workout

### ISSUE THREAD

**Issue by Vincenius** [Vincenius/workout-lol#32]
Make the videos a bit bigger depending on the screen size and let the user maximize (resize?) it.

**Comment by ngthuongdoan** [comment]
https://ant.design/components/image#components-image-demo-controlled-preview
@Vincenius You means something like this but for video right

**Comment by Vincenius** [comment]
Yeah, I was thinking of increasing the size of the videos in the modal on the preview (see screenshot). Maybe fullscreen as you proposed would make sense 🤔 

Also I'd adjust the size on the workout screen when you do the exercises.

<img width="769" alt="Screenshot 2023-07-11 at 09 33 11" src="https://github.com/Vincenius/workout-lol/assets/43953403/5e123fb0-6f2e-42b4-b30d-b0f4069e56ad">

**Comment by ngthuongdoan** [comment]
<img width="1435" alt="image" src="https://github.com/Vincenius/workout-lol/assets/45509523/b258e50d-6d58-410b-a3e7-27b5a3852115">
@Vincenius I changed to modal is it ok? I think with this size we don't need the fullscreen feature.

**Comment by Vincenius** [comment]
yeah, looks good 👍 I'll review it later today :)
