### ISSUE TITLE
Your background gradient is interesting!

### ISSUE THREAD

**Issue by inscapist** [Vincenius/workout-lol#37]
Your background gradient [here](https://github.com/Vincenius/workout-lol/blob/3f9d83bcc111e263a28afe92a14e3ce5d54886f7/components/Layout/Layout.module.css#L11) is interesting! 

How did you do it?

**Comment by Vincenius** [comment]
I got it from [gradientmagic.com](https://www.gradientmagic.com/) and customized the colors :)

**Comment by inscapist** [comment]
Thank you!
