### ISSUE TITLE
Missing <noscript>

### ISSUE THREAD

**Issue by toastal** [Vincenius/workout-lol#38]
Opening the page, the get a plain blank page with no text.

Please include a `<noscript>` element with a short description of what this application is doing so users a) get a message informing them to allow JS on the page b) understand what will happen when they do allow (this is a web app, but what kind?). Often the same text as the `<description>` can suffice.

**Comment by Vincenius** [comment]
Done in: https://github.com/Vincenius/workout-lol/pull/41
