### ISSUE TITLE
Containerized deployment

### ISSUE THREAD

**Issue by rounakdatta** [Vincenius/workout-lol#42]
Hello, amazing project!

I was looking to self-host this app, and it'd be nice if we could package the app as a container. Do you have a plan to include a Dockerfile or so ... otherwise I'd be happy to make a contribution! Thanks for the work!

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/Vincenius/workout-lol/issues/42">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/Vincenius/workout-lol/issues/42/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/Vincenius/workout-lol/issues/42/pledge.svg">
</picture>
</a>

**Comment by Vincenius** [comment]
Thanks! Yeah, that would be a great addition! Feel free to pick it up 😊
