### ISSUE TITLE
Wider view / bigger videos

### ISSUE THREAD

**Issue by Dimension4** [Vincenius/workout-lol#54]
Thank you, first of all, for creating this. I stumbled upon it at the perfect time and use it every second day now.

I'm using the site on desktop and I'm quite new to all these exercises so I heavily rely on the videos for each exercise. Unfortunately the page is quite small for me so the details in the videos are hard to figure out sometimes. It would be great if the videos were resizable or the whole UI was just wider.

I'm on a 32" 4k monitor with 150% UI scaling. This is what the UI looks like on my monitor:
![image](https://github.com/Vincenius/workout-lol/assets/11558535/cbf561c2-5207-423d-b46f-3a6d48be11d1)

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/Vincenius/workout-lol/issues/54">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/Vincenius/workout-lol/issues/54/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/Vincenius/workout-lol/issues/54/pledge.svg">
</picture>
</a>

**Comment by ngthuongdoan** [comment]
@Dimension4 hi, we can let's you click on the video and it'll fullscreen. Is it ok?

**Comment by Vincenius** [comment]
yeah that would be great!

**Comment by Dimension4** [comment]
Hey, that could work yeah. However keep in mind, from a usability point of view, I want to interact as little as possible with the site during my workout (mainly because I'm sweaty and don't want to handle the peripherals). So opening and closing every video might not be ideal.

If another solution is too much effort though, I'll gladly take the click-to-fullscreen solution. Thanks for looking into this.

**Comment by Vincenius** [comment]
We could also additionally to the fullscreen make the videos responsive so that they are bigger on desktops by default

**Comment by Dimension4** [comment]
Thanks a lot! Saw the changes today in my workout, great work.
